services:
    guzzle.http_client.class:
        class:  GuzzleHttp\Client
    billetel.base:
        abstract:  true
        arguments: ['%api_url%', '%api_authorization%', '%api_desk%', '@guzzle.http_client.class']
    billetel.artists:
        class:  Spyrit\Billetel\Client\ArtistsClient
        parent: billetel.base
    billetel.categories:
        class:  Spyrit\Billetel\Client\CategoriesClient
        parent: billetel.base
    billetel.events:
        class:  Spyrit\Billetel\Client\EventsClient
        parent: billetel.base
    billetel.groups:
        class:  Spyrit\Billetel\Client\GroupsClient
        parent: billetel.base
    billetel.places:
        class:  Spyrit\Billetel\Client\PlacesClient
        parent: billetel.base
    billetel.ticket_offices:
        class:  Spyrit\Billetel\Client\TicketOfficesClient
        parent: billetel.base

    billetel.booking.base:
        abstract: true
        arguments: ['%api_booking_url%', '%api_authorization%', '%api_desk%', '@guzzle.http_client.class']
    billetel.booking.availability:
        class: Spyrit\Billetel\Client\BookingAvailabilityClient
        parent: billetel.booking.base
    billetel.booking.cart:
        class: Spyrit\Billetel\Client\CartClient
        parent: billetel.booking.base
    billetel.booking.client:
        class: Spyrit\Billetel\Client\ClientClient
        parent: billetel.booking.base
    billetel.booking.order:
        class: Spyrit\Billetel\Client\OrderClient
        parent: billetel.booking.base
    billetel.booking.ticket:
        class: Spyrit\Billetel\Client\TicketClient
        parent: billetel.booking.base
